[data]
date_column = "periode"
target_column = "permohonan_kia"
lags = [1, 2, 3, 12]
rollings = [3, 6, 12]
add_sin_cos = true

[training]
holdout_months = 6
season_length = 12

[forecast]
blend_step = 0.02